version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ov5r979w7jek"
s3_prefix = "sam-app"
region = "us-east-1"
profile = "dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
